{"name": "test_mul[mul_failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -0.02 == 0.3", "trace": "self = <pytest_advanced.testing.test_calc.TestCalc object at 0x000001F88A9C9070>, get_calc = <pytest_advanced.calc.calc.Calculator object at 0x000001F88A997D30>\nmul_get_data = [0.1, -0.2, 0.3]\n\n    @allure.story(\"Multiplication Testing\")\n    @pytest.mark.mul\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, mul_get_data):\n        # 调用相乘方法\n        with allure.step(\"Computing the product of two numbers\"):\n            result = get_calc.mul(mul_get_data[0], mul_get_data[1])\n        if isinstance(result, float):\n            result = round(result, 2)\n        # 得到相乘结果之后写断言\n>       assert result == mul_get_data[2]\nE       assert -0.02 == 0.3\n\ntest_calc.py:74: AssertionError"}, "steps": [{"name": "Computing the product of two numbers", "status": "passed", "start": 1612429430926, "stop": 1612429430926}], "attachments": [{"name": "stdout", "source": "b2e124b8-130c-49e8-a1b0-726578ba0877-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "mul_get_data", "value": "[0.1, -0.2, 0.3]"}], "start": 1612429430926, "stop": 1612429430926, "uuid": "7dd88461-cfd9-4d26-b8a0-9d1c63892172", "historyId": "62bc23d18724f4bab9d33351facb2984", "testCaseId": "463eb02829151a13063664521f3c4534", "fullName": "test_calc.TestCalc#test_mul", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "Multiplication Testing"}, {"name": "feature", "value": "Calculator Testing"}, {"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "mul"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-D94MS34"}, {"name": "thread", "value": "20284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}